# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        brew install swiftlint
        pod install
    

    - name: Build project
      run:
          xcodebuild build -project ToDoShka.xcodeproj -scheme ToDoShka clean build -sdk iphonesimulator CODE_SIGNING_ALLOWED=No
#      xcodebuild -workspace ToDoShka.xcworkspace -scheme ToDoShka -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' build

    # - name: Build
    #   run: |
    #     xcodebuild build -workspace ToDoShka.xcworkspace -scheme ToDoShka clean build -sdk iphonesimulator CODE_SIGNING_ALLOWED=No

#    - name: Run tests
#      run: |
#        xcodebuild test -workspace ToDoShka.xcworkspace -scheme ToDoShka clean build -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14 Plus" CODE_SIGNING_ALLOWED=No
